FROM ubuntu:xenial

RUN apt-get update > /dev/null && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      python \
      python-dev \
      python-setuptools \
      python-pip \
      python3 \
      python3-dev \
      python3-setuptools \
      python3-pip \
      libffi-dev \
      libssl-dev  \
      libyaml-dev \
      ssh \
      g++

RUN pip3 install wheel

WORKDIR /work

RUN mkdir -p /var/log/tron
