[tool.ruff]
target-version = "py38"
line-length = 120
indent-width = 4
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
output-format = "github"
show-fixes = true

[tool.ruff.lint]
select = [
    "I",     # isort - import order
    "UP",    # pyupgrade
    "T10",   # debugger
    "E",     # pycodestyle
    "W",     # pycodestyle
    "F",     # pyflakes
]

ignore = [
    # pycodestyle errors
    "E203",  # whitespace before ':'
    "E231",  # missing whitespace after ','
    "E241",  # multiple spaces after ','
    "E251",  # unexpected spaces around keyword / parameter equals
    "E265",  # block comment should start with '# '
    "E501",  # line too long

    # pyupgrade
    "UP006", # pyupgrade Use `builtins.type` instead of `typing.Type` for type annotation
    "UP031", # pyupgrade Use format specifiers instead of percent format
    "UP035", # pyupgrade `typing.Type` is deprecated, use `builtins.type` instead
]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint.isort]
force-single-line = true
case-sensitive = false
lines-after-imports = 2
order-by-type = false
no-lines-before = ["future", "standard-library"]
