[tool.ruff]
target-version = "py38"
line-length = 120
indent-width = 4
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
show-fixes = true

[tool.ruff.lint]
select = [
    "I",   # isort - import order
    "UP",  # pyupgrade
    "T10", # debugger
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
]

ignore = [
    # pycodestyle errors
    "E203", # whitespace before ':'
    "E231", # missing whitespace after ','
    "E241", # multiple spaces after ','
    "E251", # unexpected spaces around keyword / parameter equals
    "E265", # block comment should start with '# '
    "E501", # line too long
    "E721", # Use is and is not for type comparisons, or isinstance() for isinstance checks
    # pyupgrade
    "UP006", # Use `builtins.type` instead of `typing.Type` for type annotation
    "UP031", # Use format specifiers instead of percent format
    "UP032", # Use f-string instead of format call
    "UP035", # `typing.Type` is deprecated, use `builtins.type` instead
    "UP036", # Version block is outdated for minimum Python version
]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint.isort]
force-single-line = true
case-sensitive = false
lines-after-imports = 2
order-by-type = false
no-lines-before = ["future", "standard-library"]
