ssh_options:
  agent: true

nodes:
  - name: node0
    hostname: 'localhost'

jobs:
  "uptime_job":
    node: node0
    schedule: "cron */10 * * * *"
    actions:
      "uptimer":
        command: "uptime"
