--- !TronConfiguration
working_dir: './working'

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node1 !Node
        hostname: 'dev2sv'
    - &node2 !Node
        hostname: 'dev3sv'

    - &pool !NodePool
        nodes: [*node1, *node2]

jobs:
    - &job0 !Job
        name: "job0"
        node: *pool
        all_nodes: True
        schedule: "interval 20s"
        queueing: False
        actions:
            - &start
                name: "actionStartEdit"
                command: "sleep 3; echo asdfasdf"
                node: *node
        cleanup_action:
            command: "echo 'cleaned up job0'"

    - &job1 !Job
        name: "job1"
        node: *node
        schedule: "interval 20s"
        queueing: False
        actions:
            - &action !Action
                name: "actionAlone"
                command: "cat big.txt; sleep 10"
services:
    -
        name: "testserv"
        node: *pool
        count: 10
        restarts: 3
        pid_file: "/var/run/%(name)s-%(instance_number)s.pid"
        command: "sleep 10; echo %! > %(pid_file)s"
        monitor: "interval 20s"
            
