--- !TronConfiguration
working_dir: "/Users/mtytel/Tron/working"

ssh_options: !SSHOptions
    agent: true

nodes:
    - &node0
        hostname: 'dev2sv'
    - &node1
        hostname: 'dev3sv'
    - &node_pool !NodePool
        nodes: [*node0, *node1]

watcher:
    - &watcherEmailSystems !EmailWatcher
        address: systems@yelp.com
        level: CRITICAL
        jobs: ALL
        services: ALL
    
    - &watcherEmailAds !EmailWatcher
        address: ads@yelp.com
        level: ERROR
        jobs: [*business_ad, *business_ad_cache]
        services: [*ad_worker]
    
    - &watcherIRC !IRCWatcher
        host: irc.yelpcorp.com
        port: 8089
        password: thePassword
        channel: yelp
        level: ERROR
        jobs: ALL
        services: ALL

jobs:
    -
        name: "interval_dag"
        node: *node0
        schedule: "interval 20s"
        actions:
            - &dag0
                name: "dag0"
                command: "sleep 3; echo 0"
            - &dag1
                name: "dag1"
                command: "sleep 3; echo 1"
                requires: *dag0
            - &dag2
                name: "dag2"
                command: "sleep 3; echo 2"
                requires: *dag0
            -
                name: "dag3"
                command: "sleep 1; echo 3"
                requires: [*dag1, *dag2]
        cleanup_action:
            command: "sleep 1; echo 'cleaned up interval_dag'"

    -
        name: "fail_dag"
        node: *node_pool
        schedule: "interval 20s"
        actions:
            - &succ0
                name: "succ0"
                command: "sleep 5; echo start"
            - &succ1
                name: "succ1"
                requires: *succ0
                command: "sleep 1; echo cancelled; sleep 1"
            - &fail
                name: "fail"
                requires: *succ0
                command: "sleep 4; echo cancelled; fdsadsfaeafaefa"
            -
                name: "end"
                requires: [*succ1, *fail]
                command: "sleep 5; echo done"
        cleanup_action:
            command: "sleep 1; echo 'cleaned up fail_dag'"

    -
        name: "constant"
        node: *node_pool
        schedule: "constant"
        actions:
            - &action_const0
                name: "constant_lead0"
                command: "sleep 5; echo constant; sleep 2"
            - &action_const1
                name: "different_node"
                node: *node0
                command: "sleep 1; echo following; sleep 2"
            - &actionFoll
                name: "follow"
                command: "sleep 1; echo following; sleep 2"
                requires: [*action_const0, *action_const1]
            
    -
        name: "daily_mws"
        node: *node_pool
        schedule: "daily 00:00:00 MWS" # All Days: MTWRFSU
        actions:
            - &actionMF
                name: "action_mws"
                command: "sleep 5; echo mws; sleep 2"

    -
        name: "daily"
        node: *node_pool
        schedule: "daily"
        actions:
            - &actionDaily
                name: "action_daily"
                command: "sleep 5; echo daily; sleep 2"

    -
        name: "queueing"
        node: *node_pool
        queueing: True
        schedule: "interval 12s"
        actions:
            - !Action
                name: "long_action"
                command: "sleep 10; echo queueing; sleep 10"

    -
        name: "cancel"
        node: *node0
        schedule: "interval 12s"
        actions:
            -
                name: "actionCancel"
                command: "sleep 10; echo cancelnext; sleep 10"

    -
        name: "fail_queue"
        node: *node_pool
        schedule: "interval 12s"
        actions:
            - &actionFailQueue
                name: "actionFailQueue1"
                command: "sleep 15; failfailfail"

    -
        name: "all_nodes"
        node: *node_pool
        all_nodes: True
        schedule: "interval 50s"
        actions:
            - &actionAddition
                name: "all_node0"
                command: "sleep 4; echo im awake"
            - &acitonWait
                name: "all_node1"
                command: "sleep 2; echo jobs done"

services:
    - 
        name: "service0"
        node: *node_pool
        enable:
            command: "sleep 4; echo enabled"
        disable:
            command: "sleep 5; echo disabled"
        monitor:
            schedule: "interval 40s"
            actions:
                - &mon0
                    name: "mon0"
                    command: "sleep 4; echo mon0"
                -
                    name: "mon1"
                    command: "sleep1; echo mon1"
                    requires: *mon0
        
