ssh_options:
  agent: true

nodes:
  - name: node0
    hostname: 'localhost'

jobs:
    -
       name: "uptime_job"
       node: node0
       schedule: "interval 10m"
       actions:
         - name: "uptimer"
           command: "uptime"
