.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH trond 8 "July 2010" Linux "User Manuals"
.SH NAME
trond \- the controlling daemon for tron
.SH SYNOPSIS
.B trond
.RB "[" "--working-dir=<working dir>" "]"
.RB "[" "--verbose" " | " "-v" "]"
.RB "[" "--debug" ]"
.SH DESCRIPTION
.B trond
is the tron daemon that manages all jobs and actions
.SH OPTIONS
.IP --working-dir
The file directory for storage of objects like config, state and stdout/stderr output
.IP --nodaemon
Indicates trond should not daemonize
.IP --pid-file
Where to store PID of the daemonized process
.IP "-l, --log-file"
Where to store logs
.IP "-P, --port"
Port to listen on (default 8089)
.IP "-H, --host"
What host to bind to (defaults to localhost)
.IP --verbose
Displays status messages along the way
.IP --debug
Enters debug mode
.SH FILES
.SH ENVIRONMENT
.SH DIAGNOSTICS
.SH BUGS
Email found bugs to yelplabs@yelp.com
.SH AUTHOR
Rhett Garber
.SH "SEE ALSO"
.BR tronview (1),
.BR tronctl (1),
.BR tronfig (1),

